#!/bin/sh

PROGDESTDIR=/usr/local/trapfwd


##
## you should not have to edit below this line
##

TRAPFWD=$PROGDESTDIR/trapfwd
OPTIONS="-d -f $PROGDESTDIR/trapfwd.cfg"

pid=`/usr/bin/ps -e | /usr/bin/grep trapfwd | /usr/bin/sed -e 's/^  *//' -e 's/ .*//'`

case $1 in
'start')
	if [ "${pid}" = "" ]
	then
		if [ -x ${TRAPFWD} ]
		then
		    ${TRAPFWD} ${OPTIONS}
		fi
	fi
	;;

'stop')
	if [ "${pid}" != "" ]
	then
		/usr/bin/kill -9 ${pid}
	fi
	;;
*)
	echo "usage: /etc/init.d/trapforwarder {start|stop}"
	;;
esac
