#!/sbin/sh
#
#

#
# SNMP Trap Forwarder from Network Computing Technologies, Inc. 
# http://www.nct-va.com
#
PROGDESTDIR=/usr/local/trapfwd
TRAPFWD=$PROGDESTDIR/trapfwd
OPTIONS="-d -f $PROGDESTDIR/trapfwd.cfg"

PATH=/sbin:/usr/sbin:/usr/bin
export PATH

rval=0
set_return() {
	x=$?
	if [ $x -ne 0 ]; then
		echo "EXIT CODE: $x"
		rval=1
	fi
}

GetNamedProcIds()

{
	ps -e | awk -v mypid=$$	-v pname=$1			\
			'$NF~pname {				\
				if ($1 != mypid)		\
					print $1		\
			}'
}

case $1 in
'start_msg')
	echo "Start SNMP Trap Forwarder daemon"
	;;

'stop_msg')
	echo "Stop SNMP Trap Forwarder daemon"
	;;

'start')
	if [ -x $TRAPFWD ]; then
		pids=`GetNamedProcIds "trapfwd"`
		if [ "X$pids" != "X" ]; then
			kill $pids 1>/dev/null 2>&1
		fi
		$TRAPFWD $OPTIONS && 
			echo "SNMP Trap Forwarder started"
		set_return
	else
		echo "Unable to start trapfwd:"
		echo "Daemon and/or conf file missing and/or incorrect permissions"
		rval=2
	fi

	;;

'stop')
	#
	# Determine PIDs of process(es) to stop
	#
	pids=`GetNamedProcIds "trapfwd"`

	kill $pids 1>/dev/null 2>&1
	echo "trapfwd stopped"

	# Set return value to be zero.

	rval=0; 

	;;

*)
	echo "usage: $0 {start|stop}"
	rval=1
	;;
esac

exit $rval
