#! /bin/sh

PROGDESTDIR=/usr/local/trapfwd


##
## you should not have to edit below this line
##

TRAPFWD=$PROGDESTDIR/trapfwd
OPTIONS="-d -f $PROGDESTDIR/trapfwd.cfg"

##
## Should be no need to edit beyond this line
##

IS_ON=/etc/chkconfig
KILLALL=/sbin/killall


if test ! -x $IS_ON ; then
    IS_ON=true
fi
if $IS_ON verbose ; then
    ECHO=echo
else		# For a quiet startup and shutdown
    ECHO=:
fi

case $1 in
'start')
	if test -x $TRAPFWD; then
	    $KILLALL -15 trapfwd
	    $ECHO "Trapfwd:\c"
	    $TRAPFWD $OPTIONS; $ECHO " trapfwd\c"
	    $ECHO "."
	fi
	;;
'stop')
	$ECHO "Stopping TrapFwd."
	$KILLALL -15 trapfwd
	exit 0
	;;
*)
	echo "usage: /etc/init.d/trapforwarder {start|stop}"
	;;
esac
